### ISSUE TITLE
createClient() with optional sessionToken

### ISSUE THREAD

**Issue by tristanls** [jed/dynamo#10]
For the use case of using `dynamo` via command line program running in a shell, it would be nice to be able to pass an optional saved session token when creating a client in order not to get rate limited by AWS Security Token Service.

``` javascript
db = dynamo.createClient({
  accessKeyId: "...",
  secretAccessKey: "...",
  sessionToken: "..." // optional saved session token
});
```

**Comment by jed** [comment]
is rate-limiting an issue? i mean, these tokens last for quite a while.

you can also override the token, which is accessible in the session at `db.account.session.sessionToken`.

**Comment by tristanls** [comment]
re: rate-limiting
AWS states in their documentation not to get a new token with every request. Because a CLI program runs and exits, it maintains no state, so it will ask for new token every time. It's this asking-for-new-token every time that will supposedly get rate-limited according to the docs. (spent some time trying to find the exact reference, but can't find it, they say it "somewhere" :D)

re: override
Yes, I assume that's the solution. Optional parameter for `createClient` is just a convenience, because as far as I can tell, createClient doesn't fetch a session token until some sort of request is initiated via the API right?

It's a corner case particular to CLI applications for sure.

**Comment by jed** [comment]
closing, as setting `db.account.session.sessionToken` is probably sufficient.
