### ISSUE TITLE
writing multibyte characters creates invalidserviceexceptions

### ISSUE THREAD

**Issue by alexbosworth** [jed/dynamo#11]
Writing a character like 人

raises this error from dynamodb

com.amazon.coral.service#InvalidSignatureException: The request signature we calculated does not match the signature you provided.

**Comment by jed** [comment]
@alexbosworth, would you mind writing up a failing test case?

**Comment by alexbosworth** [comment]
If you change line 81 of setup.js to names = ["John人", "Paul", "Ringo", "George"] it should fail I think

I have switched to https://github.com/teleportd/node-dynamodb :/ - that has some issues as well but the multibyte thing is pretty important to my use-case

**Comment by jed** [comment]
thanks for pointing this out, @alexbosworth.

**Comment by alexbosworth** [comment]
np - I wrote my own aws project - https://github.com/alexbosworth/bucket - I know it can be frustrating to work with the signatures

The chaining idea is cool, I like chaining in jquery and I'm not sure why it's not more popular in the node.js world
