### ISSUE TITLE
Feature request: Deleting items

### ISSUE THREAD

**Issue by timothyjoelwright** [jed/dynamo#12]
I wasn't able to find how to delete items in the high-level api documentation. Perhaps I overlooked something?

**Comment by jed** [comment]
thanks, @timothyjoelwright!

**Comment by timothyjoelwright** [comment]
Wow, that was fast! Thanks a lot!

**Comment by jed** [comment]
note that it doesn't support the whole DeleteItem API yet, including expectations and return values... not sure how do that cleanly yet.
