### ISSUE TITLE
Predicates + Update.when()

### ISSUE THREAD

**Issue by mpneuried** [jed/dynamo#22]
I tried to use the method `item.when(predicates)`.  
In every version passed the predicate object i could not generate a valid conditional request like:  

```
Expected: { id: { Exists: false } }
```

So i check your code and found out you forcing the value of the predicate to an array. [Predicate.js:39](https://github.com/jed/dynamo/blob/master/lib/Predicates.js#L39)

So it's only possible to get the `operator` = `NE` or `EQ`, witch where necessary to the `item.when()`, if you pass something like this:

```
new Predicate( { id: { "!=": [ undefined ] } } ) // a like bit weird ;-)
```

**Now the problem**

Within the [Update.js:28](https://github.com/jed/dynamo/blob/master/lib/Update.js#L28) you check for `null` in combination with `NE`or `EQ`. I think that this can never be reached with the current predicate implementation.

A small rewrite to make it possible to generate a valid conditional request `Update.js:28`:

```
 if (value === null || value === undefined) {
```

But this is not really a nice solution.

Can you check the method `item.when()` for conditional requests or can you tell me how to use them.

**Comment by jed** [comment]
@mpneuried, thanks for the catch.

i think this could be solved by replacing this whole block in `Update.js`:

``` javascript
    if (value === null) {
      if (operator == "EQ") {
        expectation[name] = {Exists: false}
        return this
      }

      if (operator == "NE") {
        expectation[name] = {Exists: true}
        return this
      }
    }

    if (operator == "EQ") {
      expectation[name] = {Value: value}
      return this
    }
```

with this:

``` javascript
    switch (operator) {
      case "NULL":
        expectation[name] = {Exists: false}
        return this

      case "NOT_NULL":
        expectation[name] = {Exists: true}
        return this

      case "EQ":
        expectation[name] = {Value: value}
        return this
    }
```

would this work in your case?

**Comment by mpneuried** [comment]
i'll give it a try, and tell you if it works

**Comment by mpneuried** [comment]
Works fine. Thanks !!

PS: Good work. I use your module to write a ORM-like abstraction for DynamoDB ( [simple-dynamo](https://github.com/mpneuried/simple-dynamo) ).
