### ISSUE TITLE
please tag versions on github

### ISSUE THREAD

**Issue by timbertson** [jed/dynamo#25]
(preferrably in the format "v1.2.3")

It makes tooling easier :)

**Comment by jed** [comment]
weird, i thought `npm version` would [create tags for me](http://npmjs.org/doc/version.html). noted for future commits, thanks.

**Comment by timbertson** [comment]
Ahh - In that case, you may just need to run `git push --tags` to
actually push these to github - I often forget that myself.

**Comment by jed** [comment]
ah, good point, and [done](https://github.com/jed/dynamo/tags)!
