### ISSUE TITLE
Update with an attribute set to zero does not work

### ISSUE THREAD

**Issue by scribblelive** [jed/dynamo#29]
If you try to add 0 (zero) via an update command, you get the exception: 

com.amazon.coral.validate#ValidationException: One or more parameter values were invalid: Only DELETE action is allowed when no attribute value is specified

I think the bug is in Update.js, line 60 when you check if "value" is true. Zero is false, so the value is never set. 

Thanks for the great library!

**Comment by jed** [comment]
cool, this should help. thanks, @scribblelive.

**Comment by scribblelive** [comment]
Thank you! :)
