### ISSUE TITLE
item.save(callback) not implemented

### ISSUE THREAD

**Issue by tglines** [jed/dynamo#30]
It appears that item.save(callback) is not implemented as spec'ed out in the API.

**Comment by eshao** [comment]
The problem is that (looking at the save function in Update.js) PutItem is not expected to return anything. 

So this code in Update.js:

```
if (data = data.Attributes) {
  cb(null, Attributes.prototype.parse(data))
}
```

Actually overwrites data with null, thus triggering the error line cb(), returning undefined.
