### ISSUE TITLE
AWS SDK - Doesn't seem as good as your library

### ISSUE THREAD

**Issue by techpines** [jed/dynamo#40]
I know you say that this is deprecated for the aws-sdk.  But the aws-sdk is missing all of your sweet high-level functions.

I want the blue pill :)

**Comment by jed** [comment]
well, it's deprecated, but of course as long as the API doesn't change you can use it. personally, after learning all about their API to write this, i basically realized it's hard to abstract every feature cleanly. this is why i wrote [dynamo client](https://github.com/jed/dynamo-client); i think it's worth it to just suck it up and learn the API.

ideally, the next abstraction on top of dynamo would be built on amazon's sdk, but we should wait first for it to stabilize.
