### ISSUE TITLE
error while retrieving and adding data

### ISSUE THREAD

**Issue by bhanu21** [jed/dynamo#41]
Hello 
I was trying to use dynamo module for a little class project but its not working and giving a unusual error "healthy: dynamodb.us-east-1.amazonaws.com 
^
SyntaxError: Unexpected token h  "

I am all torn out seeking out the reason for this error.
Please let me know what could be the possible error.
 here is the code that i have been trying to use
var dynamo = require("dynamo")
  , client = dynamo.createClient()
  , db = client.get("us-east-1")

db.createTable({
  TableName: "DYNAMO_TEST_TABLE_1",

  ProvisionedThroughput: {
    ReadCapacityUnits: 5,
    WriteCapacityUnits: 5
  },

  KeySchema: {
    HashKeyElement: {
      AttributeName: "hash",
      AttributeType: "S"
    }
  }
}, function(err, data){ ... }

Thanks and regards

**Comment by jed** [comment]
note: https://github.com/jed/dynamo#this-library-has-been-deprecated

**Comment by bhanu21** [comment]
Thanks Jed for the quick response.
