### ISSUE TITLE
Doc for Scan seems inconsistent, cf get() and count()?

### ISSUE THREAD

**Issue by mhart** [jed/dynamo#5]
Scan example on https://github.com/jed/dynamo/wiki/High-level-API is:

``` javascript
table.scan({
        name: "dynamo",
        iq: {">=": 100}
      })
      .get(["name", "iq", "status"])
      .count()
      .fetch(function(err, count){ ... })
```

But documentation for `scan.count()` just below this says: "cannot be used if `Scan#get()` is called"

**Comment by jed** [comment]
thanks for the catch, @mhart. fixed.
