### ISSUE TITLE
low level API - listTables error

### ISSUE THREAD

**Issue by dmvaldman** [jed/dynamo#6]
I get an error that the first argument to db.listTables(args,callback) should be a string. When I put the empty string, it seems to work, but this shouldn't be necessary. I am new to all this so another explanation is that I'm not making any sense....

Also, fleshing out the low-level api with some examples would be very helpful. I'm not exactly sure what the arguments should be like for many of the functions.

**Comment by jed** [comment]
the low-level api is that provided by amazon, verbatim. for examples, check out [their documentation](http://docs.amazonwebservices.com/amazondynamodb/latest/developerguide/API_ListTables.html).
