### ISSUE TITLE
publish latest to npm

### ISSUE THREAD

**Issue by andrewjstone** [jed/dynamo#7]
Hi Jed,

Can you please publish the latest to npm with the fix from this commit?

https://github.com/jed/dynamo/commit/51b871aada35d36e8608483de5cb9758e6b25cd7

I just spent quite a while tracking down this bug, only to realize it was already fixed on github. 

Thanks a bunch.

**Comment by jed** [comment]
my bad, @andrewjstone. it's [up now](http://search.npmjs.org/#/dynamo).

**Comment by andrewjstone** [comment]
Thanks man!
